### ISSUE TITLE
Should we limit the range of numbers?

### ISSUE THREAD

**Issue by liujiajun** [AY1920S1-CS2113T-T12-3/main#143]
For example, ingredients quantity can only be 1~10000. This could prevent the possibility of overflow.

What do you guys think?

**Comment by liushiru** [comment]
I think we should so as to minimize potential bugs.

**Comment by liujiajun** [comment]
What about limiting all numbers to 1 to 1 000 000?

**Comment by liushiru** [comment]
Not sure about complexity in implementation. But I think 5 000 is more than enough for products. Logically a small bakery business will at most100 active products. The remaining are for archive products. As for transaction and sales, the number should be larger. It does not make sense that the user has to clear the previous transactions for new sales. Consider 100 transaction per day. 36 500 per year. 365 000 for 10 years. So maybe 1 000 000 for transaction?

**Comment by liujiajun** [comment]
or so 1 000 000 for transaction and 5000 for others. All double numbers. Is it ok? @eugenelim97 @chekjun

**Comment by eugenelim97** [comment]
yes it is ok

**Comment by liujiajun** [comment]
> Not sure about complexity in implementation. But I think 5 000 is more than enough for products. Logically a small bakery business will at most100 active products. The remaining are for archive products. As for transaction and sales, the number should be larger. It does not make sense that the user has to clear the previous transactions for new sales. Consider 100 transaction per day. 36 500 per year. 365 000 for 10 years. So maybe 1 000 000 for transaction?

Well now I think 5000 may not be enough for inventory, especially when quantity unit is gram, for example. So maybe we can increase the bound?

**Comment by liushiru** [comment]
Okay
