### ISSUE TITLE
Consistent case-sensitivity

### ISSUE THREAD

**Issue by liujiajun** [AY1920S1-CS2113T-T12-3/main#192]
Inventory and Shopping list capitalize first letter, while product and order do not.

Let's make our app consistent. We need to discuss what format to follow.

**Comment by liujiajun** [comment]
Currently, Product convert `bBbb` to `BBbb`, while inv does `bBbb` -> `Bbbb`. This is very confusing. @eugenelim97 @liushiru

**Comment by liushiru** [comment]
Sorry I overlooked this discussion. Product has changed to inventory's implementation, i.e. bBbb -> Bbbb
