### ISSUE TITLE
Inventory does not handle empty name/quantity

### ISSUE THREAD

**Issue by liujiajun** [AY1920S1-CS2113T-T12-3/main#196]

**Comment by eugenelim97** [comment]
For inventory/shopping list, I made it such that name is a compulsory input. So if name is not inputted, exception will be shown: Ingredient name can take any values, and should not be blank.

If quantity is not inputted, default quantity 0.0 will be used.

**Comment by liujiajun** [comment]
the command I tried was `inv add -name apple -qty `.
The error message was `empty String` which is not formatted properly
