### ISSUE TITLE
Issues with Product

### ISSUE THREAD

**Issue by liujiajun** [AY1920S1-CS2113T-T12-3/main#197]
I'm testing the product feature. I have not done a full test but here are the problems I found.

- Magic cost "4.84". Whenever I add a product, it is always this cost. 
- Edit requires "name" field to always be present
- `product show -i 1` Product show does not work. Always pops up "Product name must present"
- Product name capitalisation. Should follow Eugene to capitalise first letter. Otherwise it is very confusing.
- Adding default ingredient. Since there should not be a "-" for default remark because Inv list does not add the dash by default
- Many commands do not support undo/redo, autocomplete
- Still allows number >= 5000

Overall, product features are very buggy and I would suggest a full test later.

**Comment by liushiru** [comment]
Sorry about the bugs. I think I did not do regression testing after changing the structure.  

At my side undo/redo supports Add, Edit, Delete, which are operations involved Model. Is it required to add undo/redo to other operations like List/show as well? 

"order add -item bread, 1" throws an exception even if there is a product named "Bread". Not sure if it's intended.

**Comment by liushiru** [comment]
Thank you for picking up the bugs

**Comment by liushiru** [comment]
And "order ==" , "order -- " switch the UI to order page as well.

**Comment by liujiajun** [comment]
Thanks for the prompt fix. 

Yes. Only those change data should support undo/redo.

Product show and list were not auto-completable -  I've fixed that

By the way, quantity upper limit is set to 50,000. You may want to update it in user guide as well.

Regarding order issue, may I clarify if you capitalise only the first letter and leave the rest unchanged. Or you caplitalize the first letter and set the rest the lower case. I think we need to be consistent as I suggested in #192. We may want to have a common utility method for that. @eugenelim97
