### ISSUE TITLE
Should we allow "entity" followed by non word chars ("sale ==") to change UI page?

### ISSUE THREAD

**Issue by liushiru** [AY1920S1-CS2113T-T12-3/main#204]
I found that now `order ---`, `sale ===` .... are a valid command to switch between pages. Should we allow that?

**Comment by liujiajun** [comment]
I think should not. I've fix order

**Comment by liushiru** [comment]
Alright. Product has already been fixed in the current version.

**Comment by liujiajun** [comment]
I've fixed sale as well. Shop and inv are harder to fix because more changes are needed.

**Comment by eugenelim97** [comment]
Ok i have fixed mine in the recent pr
