### ISSUE TITLE
Testing for Order

### ISSUE THREAD

**Issue by liushiru** [AY1920S1-CS2113T-T12-3/main#215]
Below are not  entirely bugs but not so intuitive things I would notice from the perspective of a new user

-item cake, 50 -item cake, 50  adds 50 cakes.
throw croissant not existing product. when Croissant exist
-by can take past date //can specify in the user guide. otherwise doesn't make sense to have ddl in the past
order add -item Tart,0 shows insufficient ingredients. Logically it does not use any ingredient

**Comment by liujiajun** [comment]
Thanks. Changes made accordingly
