### ISSUE TITLE
Testing for Sales

### ISSUE THREAD

**Issue by eugenelim97** [AY1920S1-CS2113T-T12-3/main#217]
input: sale --
bug: brings me to sales page. This should not happen.

input: sale add -desc blueberry pie -val 12.99 -at 30/10/2019 08:31 -rmk added chocolate toppings
bug: -at doesn't work. UI shows the current date/time irl.

input: sale add -desc 7 cartons of soy milk purchased -val 14.49 -spend sdvsdvdj
bug: -spend accepts jibberish 

input: sale edit 2 -desc 6 cartons of soy milk -val 10.35 -rmk revised quantity from 7 -at 29/05/2018 19:00
bug: UI shows jibberish date/time like May 20, 2019 00:14

input: sale edit 1 -val ---
bug: exception only says "empty string"

input: sale edit 1 -desc dff-dfgdf
bug: seems like hyphen cnnt be used as input, same goes for all the other features. Need to put in user guide.

input: sale filter -from 05/09/2014 -to 13/10/2014
bug: gives me 2019 dates very buggy

**Comment by chekjun** [comment]
Yes, noted, I'm working on it. I've fixed the sale-- and boolean but not sure why my date gives wrong.

**Comment by chekjun** [comment]
Fixed
