### ISSUE TITLE
DG

### ISSUE THREAD

**Issue by liujiajun** [AY1920S1-CS2113T-T12-3/main#251]
- Transfer DG to GitHub (NFR, user stories etc.)
- Update UML according to last week's feedback. (We should use consistent colours for different components )
- Write the section on testing.

**Comment by liujiajun** [comment]
Can you help edit respective sections (@chekju model, @eugenelim97 storage @liushiru ui). You can follow the color scheme  used in architecture section.

**Comment by chekjun** [comment]
Do I request PR as usual or can I commit changes directly for this?

**Comment by liujiajun** [comment]
> Do I request PR as usual or can I commit changes directly for this?

Both can I think
