### ISSUE TITLE
Should archived products be allowed to add into an order?

### ISSUE THREAD

**Issue by liujiajun** [AY1920S1-CS2113T-T12-3/main#263]

**Comment by liujiajun** [comment]
Also, I noted that after I filtered the product list, I cannot add items that are in product list, but not in the filtered product list to an order.

For now my solution is to add the following in UG. Do you think it is ok or we need to make changes?

> ⚠️ **WARNING**
Items that are not in the **filtered** Product List cannot be added. Filtered Product List is the list displayed on the product page. It may not contain all products available if you have previously used `product search` or `product list` to filter the list.

**Comment by liushiru** [comment]
I think it makes sense not to allow adding products in the ProductList but not in the filtered list. Users can be confused to have two products with the same name but one is active and another one is archived. Thank you for pointing this problem out. Will update UG accordingly. 

I don't think we should allow users to add an archived product to order.

**Comment by liujiajun** [comment]
I think I was trying to say, currently anything that's currently displayed in PL is allowed to be added to order, and those are not displayed, even if they are active, are not allowed. If we want to use your implementation, I will need an extra method in model to get all active product.
