### ISSUE TITLE
Change error message

### ISSUE THREAD

**Issue by eugenelim97** [AY1920S1-CS2113T-T12-3/main#278]
Input: order remove one
Input: shop remove cheese
Exception: Number format is invalid.

Number format is regarding formatting of numbers. Should change error message to "Please enter a valid index" or something like that.

What I did was catch "ParseException" instead of "IndexOutOfBoundsException", then I throw my own error message.

**Comment by liujiajun** [comment]
Thanks, I did not realise that. Check if it is fixed in #280

**Comment by eugenelim97** [comment]
Take note Sale and Product also @chekjun @liushiru

**Comment by liushiru** [comment]
Okay done, thx

**Comment by chekjun** [comment]
Mine gives "Index is invalid".
