### ISSUE TITLE
Have ProductList class

### ISSUE THREAD

**Issue by liujiajun** [AY1920S1-CS2113T-T12-3/main#86]
Is it better to have ProductList instead of RecipeList? 

A product can be something sold in the bakery that has a price and a recipe(ingredients). As far as I'm concerned, price and ingredients are most important properties since they are linked to other features (for example, sale needs price and inventory needs ingredients of each product). 

Steps and difficulty level could be nice-to-have, since I do not think a bakery manager needs to know exactly how difficult it is to make some drinks. He needs not know exactly how to make a drink as well.

**Comment by eugenelim97** [comment]
Yes, I think product would be more viable than recipe. Steps require the user to type a lot so it is quite troublesome to implement

**Comment by liujiajun** [comment]
Reached agreement in class.
