### ISSUE TITLE
Following CheckStyle to ensure code quality

### ISSUE THREAD

**Issue by liujiajun** [AY1920S1-CS2113T-T12-3/main#95]
I think it would be good if we check CheckStyle before making PR. This would save us a lot of work fixing code quality issues in the end.

There is a CheckStyle plugin that can be insalled in IntelliJ, making this process pretty hassle-free. Check out this [tutorial](https://nus-cs2103-ay1718s2.github.io/addressbook-level4/UsingCheckstyle.html)

Also, Codacy provides a report for the quality of each PR which is also very useful.

**Comment by eugenelim97** [comment]
Ok sure, will do. Thanks!
